/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Localize Backend API
 * OpenAPI spec version: v1
 */

/**
 * An organisation
 */
export interface OrganisationDTO {
    id?: string;
    createdAt?: string;
    modifiedAt?: string;
    name?: string;
    pictureUrl?: string | null;
}
