/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Localize Backend API
 * OpenAPI spec version: v1
 */

/**
 * A project
 */
export interface ProjectDTO {
    id?: string;
    createdAt?: string;
    modifiedAt?: string;
    name?: string;
}
