/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Localize Backend API
 * OpenAPI spec version: v1
 */

/**
 * A term of a project
 */
export interface TermDTO {
  id?: string;
  createdAt?: string;
  modifiedAt?: string;
  name?: string;
  description?: string | null;
  projectId?: string;
}
