/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Localize Backend API
 * OpenAPI spec version: v1
 */
import type { TranslationLanguageMetaDTO } from './translationLanguageMetaDTO';

export type TranslationWithMetaDTOAllOf = {
  language: TranslationLanguageMetaDTO;
};
