runtime: custom
env: flex

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 5

# Define your Docker container image and port
# ...

# Configure scaling settings
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.75
