/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Localize Backend API
 * OpenAPI spec version: v1
 */

/**
 * An organisation object to create
 */
export interface CreateOrganisationDTO {
    /** The (unique) name of the organisation */
    name: string;
    pictureContent?: string | null;
}
