/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Localize Backend API
 * OpenAPI spec version: v1
 */

/**
 * A term object to create
 */
export interface CreateTermDTO {
    /** The (unique) name of the term */
    name: string;
    description?: string | null;
}
