/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * Localize Backend API
 * OpenAPI spec version: v1
 */

/**
 * A user object to create
 */
export interface CreateUserDTO {
    email: string;
    password: string;
}
