/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Localize Backend API
 * OpenAPI spec version: v1
 */

/**
 * A user object to create
 */
export interface CreateUserDTO {
    email: string;
    firstName: string;
    lastName: string;
    password: string;
}
