/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Localize Backend API
 * OpenAPI spec version: v1
 */

export type GetOrganisationsForUserParams = {
    page?: number;
    size?: number;
    q?: string;
};
