/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * Localize Backend API
 * OpenAPI spec version: v1
 */

export type GetOrganisationsForUserParams = {
    /**
     * The current page
     */
    page?: number;
    /**
     * The current size
     */
    size?: number;
    /**
     * The search string
     */
    q?: string;
};
