/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * Localize Backend API
 * OpenAPI spec version: v1
 */
import type { LanguageDTO } from './languageDTO';

/**
 * A paging
 */
export interface LanguagePagingDTO {
    /** The languages */
    data: LanguageDTO[];
    /** The number of pages */
    nbPages: number;
    /** The current page */
    page: number;
    /** The current size */
    size: number;
    /** The total amount of languages */
    totalAmount: number;
}
