/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * Localize Backend API
 * OpenAPI spec version: v1
 */

/**
 * A language of a project
 */
export interface LanguageDTO {
    id: string;
    name: string;
    abbreviation: string;
    isSource: boolean;
    projectId: string;
}
