/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * Localize Backend API
 * OpenAPI spec version: v1
 */

/**
 * Logged in user informations
 */
export interface MeDTO {
    userId?: string;
    /** The last used organisation id */
    organisationId?: string | null;
    email?: string;
    firstName?: string;
    lastName?: string;
}
