/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * Localize Backend API
 * OpenAPI spec version: v1
 */

/**
 * A translation object to save
 */
export interface SaveTranslationDTO {
    /** The translation of a term for a language */
    translation?: string;
}
