/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Localize Backend API
 * OpenAPI spec version: v1
 */

/**
 * An organisation object to update
 */
export interface SwitchUserOrganisationDTO {
    organisationId: string;
}
