/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Localize Backend API
 * OpenAPI spec version: v1
 */

/**
 * The language linked to a translation
 */
export interface TranslationLanguageMetaDTO {
    name?: string;
    abbreviation?: string;
    isSource?: boolean;
}
