/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Localize Backend API
 * OpenAPI spec version: v1
 */
import type { TranslationDTO } from './translationDTO';
import type { TranslationWithMetaDTOAllOf } from './translationWithMetaDTOAllOf';

export type TranslationWithMetaDTO = TranslationDTO &
    TranslationWithMetaDTOAllOf;
