/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Localize Backend API
 * OpenAPI spec version: v1
 */

/**
 * A translation of a term for a language
 */
export interface TranslationDTO {
    languageId?: string;
    termId?: string;
    translation?: string;
}
