/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * Localize Backend API
 * OpenAPI spec version: v1
 */

/**
 * An organisation object to update
 */
export interface UpdateOrganisationDTO {
    /** The (unique) name of the organisation */
    name: string;
    pictureContent?: string | null;
}
