/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Localize Backend API
 * OpenAPI spec version: v1
 */

/**
 * A term object to update
 */
export interface UpdateTermDTO {
    /** The (unique) name of the term */
    name: string;
    description?: string | null;
}
