/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Localize Backend API
 * OpenAPI spec version: v1
 */

/**
 * A language
 */
export interface UpsertProjectLanguageDTO {
    name: string;
    abbreviation: string;
}
