/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * Localize Backend API
 * OpenAPI spec version: v1
 */

/**
 * A user
 */
export interface UserDTO {
    id?: string;
    createdAt?: string;
    modifiedAt?: string;
    email?: string;
}
