/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * Localize Backend API
 * OpenAPI spec version: v1
 */

/**
 * A membership with user
 */
export interface UserWithMembershipDTO {
    id?: string;
    email?: string;
    role?: string;
    createdAt?: string;
    modifiedAt?: string;
}
