/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * Localize Backend API
 * OpenAPI spec version: v1
 */
import type { UserWithMembershipDTO } from './userWithMembershipDTO';

/**
 * A paging
 */
export interface UserWithMembershipPagingDTO {
    /** The users */
    data?: UserWithMembershipDTO[];
    /** The number of pages */
    nbPages?: number;
    /** The current page */
    page?: number;
    /** The current size */
    size?: number;
    /** The total amount of users */
    totalAmount?: number;
}
